### ISSUE TITLE
The input is env_url not enviornment_url

### ISSUE THREAD

**Issue by kylepeeler** [avakar/set-deployment-status#6]
At the bottom of the README, it states to use `enviornment_url`, but it's actually `env_url` according to this output after running the action

```
Unexpected input(s) 'environment_url', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref', 'env', 'transient', 'deployment_id', 'env_url', 'status']
```

I'll make a pr to update the docs so it says env_url!

**Comment by avakar** [comment]
I think it really is `environment_url`, see https://github.com/avakar/set-deployment-status/blob/master/index.js#L20. I'll try to repro this tomorrow, but could you please recheck in the meantime?

**Comment by kylepeeler** [comment]
Oops, I was referencing a different package, apologies!
